//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShoppingStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {

        public int ProductId { get; set; }

        [Required]
        //[RegularExpression(@"^[A-Z]+[a-zA-Z''-'\s\-]*$", ErrorMessage ="The first letter of product name should be a capital")]  
        public string Name { get; set; }

        [Required]
        //[RegularExpression(@"^[A-Z]+[a-zA-Z''-'\s\-]*$", ErrorMessage = "The first letter of product description should be a capital")]
        public string Description { get; set; }

        [Required]
        [Range(0.01, Double.MaxValue, ErrorMessage = "Product price should be at least between £0.01")]
        [DataType(DataType.Currency)]
        public decimal Price { get; set; }

        [Required]
        //[RegularExpression(@"^[A-Z]+[a-zA-Z''-'\s\-]*$", ErrorMessage = "The first letter of product category should be a capital")]
        public string Category { get; set; }


        //[RegularExpression(@"^https?://(?:[a-z0-9\-]+\.)+[a-z]{2,6}(?:/[^/#?]+)+\.(?:jpg|gif|png)$", ErrorMessage ="Product image should end in jpg, gif, png")]
        public string ImageUrl { get; set; }


        [RegularExpression(@"^[a-zA-Z0-9]+(?:,[a-zA-Z0-9]+)*$", ErrorMessage = "Enter all available sizes separated by a comma ONLY (No spaces)")]
        public string SizeRange { get; set; }


        [RegularExpression(@"^[a-zA-Z0-9]+(?:,[a-zA-Z]+)*$", ErrorMessage = "Enter all available colours separated by a comma ONLY (No spaces)")]
        public string AvailableColours { get; set; }
    }
}
